### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by ianwestcott** [claui/homebrew-public#6]
The README for https://github.com/claui/aws-credential-1password recommends installing the credential helper via Homebrew. However, the [formula defined in this repo](https://github.com/claui/homebrew-public/blob/36df9eef2056b4639f858e9b952552ff6b8003bb/Formula/op-aws-credentials-client.rb) currently contains a different version of the credential helper script that does not support 1Password CLI v2.

Would it be possible to update the Homebrew formula to install the latest version of the credential helper?

Thank you!

**Comment by claui** [comment]
@ianwestcott Fixed, thanks for the heads up!

**Comment by ianwestcott** [comment]
I've confirmed that the new version works for me. Thank you for the speedy resolution!
